### ISSUE TITLE
Random PVR errors while playing

### ISSUE THREAD

**Issue by SoCuul** [Leo-C/Kodi_autoplay#1]
Hi! Can't express how happy I've been with this plugin, it's been a breeze to use.

Unfortunately, every so often a message pops up on screen along the lines of "PVR add-ons not enabled" which takes over the playing video. Eventually since the message stays the same, the screen dims and stays in that state until rebooted.

**Comment by Leo-C** [comment]
Hi, many thanks for your appreciation.

My addon is not related with PVR, then I think this is related to RasPi configuration in general.
Please, try to disable PVR (if you don't need it)

**Comment by SoCuul** [comment]
Was able to confirm that removing the PVR addon fixed all the problems that I was experiencing!
